### ISSUE TITLE
Type error here when trying to run the first plugin

### ISSUE THREAD

**Issue by ibolton336** [gashcrumb/dynamic-plugins-getting-started#1]
➜  simple-chat-backend git:(main) ✗ yarn start
yarn run v1.22.19
$ backstage-cli package start
/Users/ibolton/Development/dynamic-plugins-getting-started/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/createSpecializedBackend.ts:30
    if (exists.has(service.id)) {
                           ^

TypeError: Cannot read properties of undefined (reading 'id')
    at Object.createSpecializedBackend (/Users/ibolton/Development/dynamic-plugins-getting-started/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/createSpecializedBackend.ts:30:28)
    at createBackend (/Users/ibolton/Development/dynamic-plugins-getting-started/node_modules/@backstage/backend-defaults/src/CreateBackend.ts:69:10)
    at Object.<anonymous> (/Users/ibolton/Development/dynamic-plugins-getting-started/plugins/simple-chat-backend/dev/index.ts:3:30)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._compile (/Users/ibolton/Development/dynamic-plugins-getting-started/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Object.newLoader [as .ts] (/Users/ibolton/Development/dynamic-plugins-getting-started/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)

Node.js v20.12.2

**Comment by ibolton336** [comment]
Upgrading yarn fixed this.
